server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: cinemaModule
          uri: https://challenge6-production-49c1.up.railway.app:8081/
          predicates:
            - Path=/api/v1/cinema/**